#!/usr/bin/env python3
"""Scheduler worker loop for reflect jobs (v0.1, default dry-run)."""

from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOOLS_SCHED = Path(__file__).resolve().parent
TOOLS_MEMORY = ROOT / "tools" / "memory"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(TOOLS_SCHED) not in sys.path:
    sys.path.insert(0, str(TOOLS_SCHED))
if str(TOOLS_MEMORY) not in sys.path:
    sys.path.insert(0, str(TOOLS_MEMORY))

import memory_index_v0_1 as mi  # noqa: E402
import scheduler_v0_1 as sch  # noqa: E402
from core.persona_confirmation_queue_v0_1 import (  # noqa: E402
    build_apply_plan,
    enqueue_from_routed,
    execute_apply_plan,
    init_db as init_pcq_db,
)
from core.reflect_gate_v0_1 import route_proposals  # noqa: E402


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _write_json(path: Path, payload: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _summarize_fact_lines(facts: list[dict], n: int = 3) -> list[str]:
    out = []
    for f in facts[:n]:
        content = str(f.get("content") or "").strip()
        src = str(f.get("source_ref") or "")
        if content:
            out.append(f"- {content} _(source: {src})_")
    return out


def build_reflect_proposals(reflection: dict, job_id: str) -> list[dict]:
    proposals: list[dict] = []

    # low-risk entity summary sync proposals (auto path)
    for idx, summary in enumerate(reflection.get("entity_summaries", [])[:8], start=1):
        entity = str(summary.get("entity") or f"entity_{idx}")
        facts = summary.get("top_facts") or []
        evidence = [x.get("source_ref") for x in facts if isinstance(x, dict) and x.get("source_ref")]
        if not evidence:
            continue

        slug = mi.slugify(entity)
        lines = [
            f"# {entity}",
            "",
            "> Auto-generated by reflect scheduler worker (proposal).",
            "",
            "## Facts",
            *_summarize_fact_lines(facts),
            "",
        ]

        proposals.append(
            {
                "proposal_id": f"p_entity_{job_id}_{idx}",
                "job_id": job_id,
                "operation": "upsert",
                "target_type": "opinion",
                "target_id": f"entity_summary_{slug}",
                "risk_score": 25,
                "evidence_refs": evidence[:5],
                "confidence_before": 0.65,
                "confidence_after": 0.68,
                "payload": {
                    "path": f"bank/entities/{slug}.md",
                    "content": "\n".join(lines),
                    "write_mode": "replace",
                },
            }
        )

    # high-risk conflict proposals (must human-review)
    for g in reflection.get("opinion_conflict_groups", [])[:20]:
        if not g.get("has_conflict"):
            continue
        gid = str(g.get("group_id") or "group")
        entities = [str(x) for x in (g.get("entities") or []) if str(x)]
        pc = g.get("polarity_counts") or {}
        items = g.get("items") or []
        evidence = [x.get("source_ref") for x in items if isinstance(x, dict) and x.get("source_ref")][:8]
        if len(evidence) < 2:
            evidence = evidence + [f"opinion_group:{gid}"]

        content_lines = [
            f"# Conflict Group {gid}",
            "",
            f"entities: {' '.join('@'+e for e in entities)}",
            f"topic_signature: {g.get('topic_signature')}",
            f"polarity: +{pc.get('positive',0)} / -{pc.get('negative',0)} / ={pc.get('neutral',0)}",
            "",
            "## Evidence",
        ]
        for item in items[:3]:
            content_lines.append(
                f"- [{item.get('label')}] {item.get('content')} _(source: {item.get('source_ref')})_"
            )
        content_lines.append("")

        proposals.append(
            {
                "proposal_id": f"p_conflict_{gid}",
                "job_id": job_id,
                "operation": "overwrite",
                "target_type": "persona_trait",
                "target_id": gid,
                "risk_score": 82,
                "contradiction_detected": True,
                "evidence_refs": evidence,
                "confidence_before": 0.6,
                "confidence_after": 0.85,
                "payload": {
                    "path": f"bank/review/{gid}.md",
                    "content": "\n".join(content_lines),
                    "write_mode": "replace",
                },
            }
        )

    return proposals


def process_reflect_job(
    *,
    scheduler_conn,
    job: dict,
    workspace: Path,
    reports_dir: Path,
    memory_index_db: Path,
    gate_config: str | None,
    since_days: int,
    dry_run_apply: bool,
    queue_deadline_minutes: int,
    queue_fallback_policy: str,
):
    job_id = str(job["job_id"])
    job_dir = reports_dir / job_id
    job_dir.mkdir(parents=True, exist_ok=True)

    mi_conn = mi.connect(memory_index_db)
    mi.init_db(mi_conn)
    reindex_stats = mi.cmd_reindex(mi_conn, workspace=workspace, incremental=True, retry_failures=True, max_retries=3)
    reflection = mi.cmd_reflect(
        mi_conn,
        since_days=since_days,
        workspace=workspace,
        writeback=False,
        max_per_entity=8,
        max_opinions=50,
    )

    proposals = build_reflect_proposals(reflection, job_id=job_id)
    proposals_file = job_dir / "proposals.json"
    _write_json(proposals_file, proposals)

    routed = route_proposals(str(proposals_file), config_path=gate_config, output_path=str(job_dir / "routed.json"))

    queue_result = enqueue_from_routed(
        scheduler_conn,
        routed,
        only_persona_conflict=True,
        deadline_minutes=max(1, int(queue_deadline_minutes)),
        fallback_policy=queue_fallback_policy,
    )

    apply_plan = build_apply_plan(scheduler_conn, routed)
    _write_json(job_dir / "apply_plan.json", apply_plan)

    apply_exec = execute_apply_plan(
        scheduler_conn,
        workspace=workspace,
        apply_plan=apply_plan,
        dry_run=dry_run_apply,
    )
    _write_json(job_dir / "apply_exec.json", apply_exec)

    summary = {
        "ok": True,
        "job_id": job_id,
        "mode": "dry-run" if dry_run_apply else "apply",
        "reindex": {k: reindex_stats.get(k) for k in ["docs", "facts", "failed", "skipped"]},
        "reflection": {
            "entity_summaries": len(reflection.get("entity_summaries", [])),
            "opinion_candidates": len(reflection.get("opinion_candidates", [])),
            "opinion_conflict_groups": len(reflection.get("opinion_conflict_groups", [])),
        },
        "proposals": len(proposals),
        "routed": routed.get("counts", {}),
        "queue": queue_result,
        "apply_plan": {
            "apply_count": apply_plan.get("apply_count", 0),
            "blocked_count": apply_plan.get("blocked_count", 0),
        },
        "apply_exec": {
            "applied": apply_exec.get("applied", 0),
            "deduplicated": apply_exec.get("deduplicated", 0),
            "skipped": apply_exec.get("skipped", 0),
            "failed": apply_exec.get("failed", 0),
        },
        "artifacts_dir": str(job_dir),
    }
    _write_json(job_dir / "summary.json", summary)

    if int(apply_exec.get("failed", 0)) > 0:
        raise RuntimeError(f"apply_exec failed for {job_id}: {apply_exec.get('failed')} rows")

    return summary


def run_loop(args):
    db = Path(args.db).expanduser().resolve()
    db.parent.mkdir(parents=True, exist_ok=True)

    workspace = Path(args.workspace).expanduser().resolve()
    reports_dir = Path(args.reports_dir).expanduser().resolve()
    memory_index_db = Path(args.memory_index_db).expanduser().resolve()
    memory_index_db.parent.mkdir(parents=True, exist_ok=True)

    c = sch.conn(db)
    sch.init_db(c)
    init_pcq_db(c)

    loops = 0
    processed = 0
    succeeded = 0
    failed = 0

    while True:
        loops += 1
        jobs = sch.pull_due(
            c,
            worker_id=args.worker_id,
            now=now_iso(),
            limit=max(1, int(args.pull_limit)),
            lease_sec=max(1, int(args.lease_sec)),
            actions={"reflect"},
        )

        if not jobs and args.run_once:
            break

        if not jobs:
            if args.max_loops and loops >= args.max_loops:
                break
            time.sleep(max(1, int(args.interval_sec)))
            continue

        for job in jobs:
            processed += 1
            job_id = str(job["job_id"])
            try:
                if str(job.get("action")) != "reflect" or str(job.get("object_type")) != "reflect_job":
                    raise ValueError(
                        f"unsupported job type/action: {job.get('object_type')}:{job.get('action')}"
                    )

                process_reflect_job(
                    scheduler_conn=c,
                    job=job,
                    workspace=workspace,
                    reports_dir=reports_dir,
                    memory_index_db=memory_index_db,
                    gate_config=args.gate_config,
                    since_days=max(1, int(args.since_days)),
                    dry_run_apply=not args.apply,
                    queue_deadline_minutes=max(1, int(args.queue_deadline_minutes)),
                    queue_fallback_policy=args.queue_fallback_policy,
                )
                sch.ack(
                    c,
                    job_id,
                    worker_id=args.worker_id,
                    lease_token=str(job.get("lease_token") or ""),
                )
                succeeded += 1
            except Exception as e:
                sch.fail(
                    c,
                    job_id,
                    error=str(e),
                    retry_delay_sec=max(1, int(args.retry_delay_sec)),
                    worker_id=args.worker_id,
                    lease_token=str(job.get("lease_token") or ""),
                )
                failed += 1

        if args.run_once:
            break
        if args.max_loops and loops >= args.max_loops:
            break
        time.sleep(max(1, int(args.interval_sec)))

    out = {
        "ok": failed == 0,
        "worker_id": args.worker_id,
        "db": str(db),
        "workspace": str(workspace),
        "reports_dir": str(reports_dir),
        "memory_index_db": str(memory_index_db),
        "mode": "apply" if args.apply else "dry-run",
        "loops": loops,
        "processed": processed,
        "succeeded": succeeded,
        "failed": failed,
    }
    print(json.dumps(out, ensure_ascii=False, indent=2))


def main():
    p = argparse.ArgumentParser(description="Reflect scheduler worker loop v0.1")
    p.add_argument("--db", default=str(ROOT / "data" / "mindkernel_v0_1.sqlite"), help="scheduler sqlite path")
    p.add_argument("--workspace", default=str(ROOT), help="workspace root path")
    p.add_argument("--memory-index-db", default=str(ROOT / ".memory" / "index.sqlite"), help="memory index sqlite path")
    p.add_argument("--reports-dir", default=str(ROOT / "reports" / "reflect_scheduler"), help="artifacts output dir")
    p.add_argument("--worker-id", default="reflect-worker-1")
    p.add_argument("--pull-limit", type=int, default=20)
    p.add_argument("--lease-sec", type=int, default=120)
    p.add_argument("--since-days", type=int, default=30)
    p.add_argument("--gate-config", help="optional reflect gate config json path")
    p.add_argument("--queue-deadline-minutes", type=int, default=60)
    p.add_argument("--queue-fallback-policy", default="defer")
    p.add_argument("--retry-delay-sec", type=int, default=120)
    p.add_argument("--interval-sec", type=int, default=5)
    p.add_argument("--max-loops", type=int, default=0, help="0 means unlimited")
    p.add_argument("--run-once", action="store_true", help="run one pull-process cycle and exit")
    p.add_argument("--apply", action="store_true", help="execute apply writeback (default dry-run)")
    args = p.parse_args()

    run_loop(args)


if __name__ == "__main__":
    main()
